---
- name: copy files
  hosts: docker
  tasks:
    - name: copy src to dest
      ansible.builtin.copy:
        src: /home/admin/ansible/project/real-estate-html-template/
        dest: /home/node/project/
        force: 1

