---
- name: create directory if os is ubuntu
  hosts: test
  tasks:
    - name: create directory
      ansible.builtin.file:
        path: /home/node/os
        state: directory
      when: ansible_os_family == "RedHat"
