- name: configure yum
  hosts: all
  tasks:
    - name: Add multiple repositories into the same file (1/2)
      yum_repository:
        name: AppStream
        description: AppStream
        file: AppStream
        baseurl: file:///mnt/AppStream
        gpgcheck: 0
        enabled: 1
    - name: Add multiple repositories into the same file (1/2)
      yum_repository:
        name: BaseOS
        description: baseos
        file: baseOS
        baseurl: file:///mnt/BaseOS
        gpgcheck: 0
        enabled: 1


